import './globals.css';
import HeroProvider from '@/providers/HeroProvider';
import { ThemeProvider } from 'next-themes';
import AuthProvider from '@/context/AuthContext';
import Header from '@/components/Header';

export const metadata = {
    title: 'Beautivia Shop',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <AuthProvider>
                    <HeroProvider>
                        <ThemeProvider
                            attribute="data-theme"
                            defaultTheme="system"
                            enableSystem
                            storageKey="preferred-theme" // custom localStorage key
                        >
                            <Header />
                            <main className="bg-white text-black dark:bg-gray-950 dark:text-white">
                                {children}
                            </main>
                        </ThemeProvider>
                    </HeroProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
