import '../globals.css';
// import HeroProvider from '@/providers/HeroProvider';
// import { ThemeProvider } from 'next-themes';
// import AuthProvider from '@/context/AuthContext';
// import Header from '@/components/Header';

export const metadata = {
    title: 'Admin - Beautivia Shop',
    description: 'Generated by create next app',
};

export default function AdminLayout({ children }) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <main className="bg-white text-black dark:bg-gray-950 dark:text-white">
                    {children}
                </main>
            </body>
        </html>
    );
}
