import '../globals.css';
import HeroProvider from '@/providers/HeroProvider';
import AuthProvider from '@/context/AuthContext';
import Header from '@/components/Header';

export const metadata = {
    title: 'Beautivia Shop',
    description: 'Generated by create next app',
};

export default function SiteLayout({ children }) {
    return (
        <html lang="en">
            <body className={`antialiased dark:bg-gray-950! dark:text-white`}>
                <AuthProvider>
                    <HeroProvider>
                        <Header />
                        <main className="bg-white text-black dark:bg-gray-950 dark:text-white">
                            {children}
                        </main>
                    </HeroProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
