import '../globals.css';
import HeroProvider from '@/providers/HeroProvider';
// import AuthProvider from '@/context/AuthContext';
import Header from '@/components/Header';
import Footer from '@/components/footer';

export const metadata = {
    title: 'Beautivia Shop',
    description: 'Generated by create next app',
};

export default function SiteLayout({ children }) {
    return (
        <>
            <Header />
            <main className="bg-white text-black dark:bg-gray-950 dark:text-white">
                {children}
            </main>
            <Footer />
        </>
    );
}
